device: 'cpu'

colorize_model:
  checkpoint: backend/color_model_checkpoints/best_model_FPN_21-4-23.h5

detection_model:
  yolox_m:
    config: backend/mmdetection/configs/bacteria_yolox_m_8x8_300e_coco.py
    checkpoint: backend/mmdetection/checkpoints/best_bbox_mAP_yolox.pth

  crcnn_r250 :
    config: backend/mmdetection/configs/bacteria_r2_50dcn_dyhead.py
    checkpoint: backend/mmdetection/checkpoints//best_bbox_mAP_cascade_rcnn_r2_50.pth

  crcnn_r2101 :
    config: backend/mmdetection/configs/bacteria_r2_101dcn_dyhead.py
    checkpoint: backend/mmdetection/checkpoints//best_bbox_mAP_cascade_rcnn_r2_101.pth

segmentation_model: 'backend/deepmac_1024x1024_coco17/saved_model'